package com.builtbroken.mc.fluids.fluid;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;

import java.util.ArrayList;
import java.util.List;

/**
 * @see <a href="https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/license.md">License</a> for what you can and can't do with the code.
 * Created by Dark(DarkGuardsman, Robert) on 6/30/2017.
 */
public class FluidHelper
{
    /** List of fluids generated by this mod */
    public static List<Fluid> generatedFluids = new ArrayList();
    /** List of fluid blocks generated by this mod */
    public static List<BlockSimpleFluid> generatedFluidBlocks = new ArrayList();

    /**
     * Used to quickly create a new fluid with block
     *
     * @param name
     * @return
     */
    public static Fluid createOrGetFluid(String name)
    {
        Fluid fluid;
        if (FluidRegistry.getFluid(name) == null)
        {
            fluid = new FluidVE(name);
            if (!FluidRegistry.registerFluid(fluid))
            {
                //Should never happen
                throw new RuntimeException("Failed to register fluid[" + name + "] even though one is not registered");
            }
            generatedFluids.add(fluid);
        }
        else
        {
            fluid = FluidRegistry.getFluid(name);
        }
        return fluid;
    }

    public static void createBlockForFluidIfMissing(Fluid fluid)
    {
        if (fluid.getBlock() == null) //TODO add config to disable block
        {
            String name = fluid.getName();
            BlockSimpleFluid block = new BlockSimpleFluid(fluid, name, "fluid");
            String blockName = "veBlock" + name.substring(0, 1).toUpperCase() + name.substring(1, name.length());
            GameRegistry.registerBlock(block, blockName);
            FluidHelper.generatedFluidBlocks.add(block);
        }
    }
}
